XLSX_FLD_MODEL: str = 'Model'
XLSX_FLD_REGION: str = 'Region'
XLSX_FLD_SCENARIO: str = 'Scenario'
XLSX_FLD_UNIT: str = 'Unit'
XLSX_FLD_VARIABLE: str = 'Variable'
XLSX_FIELDS: list[str] = [XLSX_FLD_MODEL, XLSX_FLD_SCENARIO, XLSX_FLD_REGION, XLSX_FLD_VARIABLE, XLSX_FLD_UNIT]

CSV_FLD_POP: str = 'Pop'
CSV_FLD_NEWCONNECTIONS: str = 'NewConnections'
CSV_FLD_INVESTMENTCOST: str = 'InvestmentCost'
CSV_FLD_NEWCAPACITY: str = 'NewCapacity'
CSV_COLUMNS: tuple[str, ...] = (CSV_FLD_POP, CSV_FLD_NEWCONNECTIONS, CSV_FLD_INVESTMENTCOST, CSV_FLD_NEWCAPACITY)
CSV_FLD_ELECPOPCALIB: str = 'ElecPopCalib'
CSV_FLD_MINIMUMOVERALL: str = 'MinimumOverall'
